# Generated by Django 4.1.3 on 2024-07-14 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype_name', models.CharField(max_length=113)),
                ('archetype_personality', models.CharField(max_length=1369)),
                ('archetype_background', models.CharField(max_length=1369)),
                ('archetype_objectives', models.CharField(max_length=1369)),
                ('archetype_a_quote', models.CharField(max_length=1369)),
                ('archetype_force_sensitive', models.BooleanField(default=False)),
                ('archetype_dexiterity', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_knowledge', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_mechanical', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_perception', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_strength', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_technical', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_force_control', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_force_sense', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_force_alter', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_starting_credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=113)),
                ('image', models.CharField(max_length=223)),
                ('name', models.CharField(max_length=69)),
                ('species', models.CharField(max_length=69)),
                ('homeworld', models.CharField(max_length=69)),
                ('gender', models.CharField(max_length=13)),
                ('age', models.IntegerField(default=21)),
                ('height', models.CharField(max_length=13)),
                ('weight', models.CharField(max_length=13)),
                ('physical_description', models.CharField(max_length=1369)),
                ('personality', models.CharField(max_length=1369)),
                ('background', models.CharField(max_length=1369)),
                ('objectives', models.CharField(max_length=1369)),
                ('a_quote', models.CharField(max_length=1369)),
                ('credits', models.IntegerField(default=0)),
                ('force_sensitive', models.BooleanField(default=False)),
                ('dexiterity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('knowledge', models.DecimalField(decimal_places=2, max_digits=2)),
                ('mechanical', models.DecimalField(decimal_places=2, max_digits=2)),
                ('perception', models.DecimalField(decimal_places=2, max_digits=2)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=2)),
                ('technical', models.DecimalField(decimal_places=2, max_digits=2)),
                ('force_control', models.DecimalField(decimal_places=2, max_digits=2)),
                ('force_sense', models.DecimalField(decimal_places=2, max_digits=2)),
                ('force_alter', models.DecimalField(decimal_places=2, max_digits=2)),
                ('force_points', models.DecimalField(decimal_places=1, max_digits=2)),
                ('dark_side_points', models.DecimalField(decimal_places=1, max_digits=2)),
                ('force_strength', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='tasks.archetype')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=269)),
                ('equipment_category', models.CharField(max_length=269)),
                ('equipment_sub_category', models.CharField(blank=True, max_length=269, null=True)),
                ('equipment_model', models.CharField(blank=True, max_length=269, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=113, null=True)),
                ('equipment_scale', models.CharField(blank=True, max_length=113, null=True)),
                ('equipment_cost', models.IntegerField(default=0)),
                ('equipment_description', models.CharField(blank=True, max_length=1369, null=True)),
                ('equipment_availability', models.CharField(blank=True, max_length=26, null=True)),
                ('equipment_skill', models.CharField(blank=True, max_length=113, null=True)),
                ('equipment_damage', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('equipment_ammo', models.IntegerField(blank=True, default=0, null=True)),
                ('equipment_charges', models.IntegerField(blank=True, default=0, null=True)),
                ('equipment_uses', models.IntegerField(blank=True, default=0, null=True)),
                ('equipment_use_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('source', models.CharField(blank=True, max_length=1369, null=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('temporary_field', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=69)),
                ('bio', models.CharField(max_length=69)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=23)),
                ('attack_range', models.IntegerField(default=1)),
                ('damage', models.DecimalField(decimal_places=1, max_digits=2)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='tasks.character')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_ability_name', models.CharField(max_length=26)),
                ('special_ability_description', models.CharField(max_length=666)),
                ('special_ability_notes', models.CharField(max_length=666)),
                ('special_ability_code', models.DecimalField(decimal_places=1, max_digits=2)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_abilities', to='tasks.character')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=26)),
                ('skill_name', models.CharField(max_length=26)),
                ('skill_code', models.DecimalField(decimal_places=1, max_digits=2)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='tasks.character')),
            ],
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession_name', models.CharField(max_length=69)),
                ('description', models.CharField(max_length=666)),
                ('possession_note', models.CharField(max_length=666)),
                ('quantity', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possessions', to='tasks.character')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=1369)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.character')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stun_level', models.IntegerField(default=0)),
                ('wound_level', models.IntegerField(default=0)),
                ('incapacitated', models.BooleanField(verbose_name=False)),
                ('mortally_wounded', models.BooleanField(verbose_name=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healths', to='tasks.character')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.CharField(max_length=666)),
                ('xp_gained', models.IntegerField(default=0)),
                ('earth_date', models.DateField(default=datetime.date(2024, 6, 11))),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='tasks.character')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeOrFlaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_or_flaw_name', models.CharField(max_length=69)),
                ('description', models.CharField(max_length=666)),
                ('bonus', models.DecimalField(decimal_places=1, max_digits=2)),
                ('edge', models.BooleanField(verbose_name=False)),
                ('flaw', models.BooleanField(verbose_name=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_or_flaws', to='tasks.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_equipment', to='tasks.character')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_name', models.CharField(max_length=23)),
                ('strength_bonus', models.DecimalField(decimal_places=1, max_digits=2)),
                ('dexterity_penalty', models.DecimalField(decimal_places=1, max_digits=2)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armors', to='tasks.character')),
            ],
        ),
        migrations.CreateModel(
            name='ArchetypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archhetype_equipment', to='tasks.archetype')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.equipment')),
            ],
        ),
    ]
